server:
  port: 8080

spring:
  application:
    name: crud-mysql-demo-hbk   #it is used by spring cloud project like eureka
  jpa:
    show-sql: true    #this helps to see sql queries in logs
    hibernate:
      ddl-auto: create-drop   #this creates new table before application starts and drop table after application ends
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: testuser